### ISSUE TITLE
Watch for multiple beacons?

### ISSUE THREAD

**Issue by aleberguer** [RadiusNetworks/hello-proximity-cordova#10]
Hello, I have the project running, and I have information from one beacon. 
My problem is when I want to get the information from multiple beacons. I did not find in the documentation, any function that returns this information. Is it available through an event or function? How can I get the RSSI values of all beacons at a given moment?

Thank you.

**Comment by jnebeker** [comment]
If you have more than one beacon in your kit on Proximity Kit (or you have a region configured in your kit that encompasses multiple beacons) and these beacons are broadcasting near your device, you should receive more than one beacon in the callbacks that are sent to the `successHandler` that you pass in when calling `watchProximity`.  A beacon will only be detected if it is included in your kit.

RSSI is available in the beacon data that is included in the `didRangeBeacon` event.  See this link for more info about the beacon data:

https://github.com/RadiusNetworks/proximitykit-plugin-cordova#beacon-data
