### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by bitdynamicsapps** [RadiusNetworks/hello-proximity-cordova#8]
I want to use [Sourcegraph](https://sourcegraph.com) for hello-proximity-cordova code search, browsing, and usage examples. Can an admin enable Sourcegraph for this repository? Just go to https://sourcegraph.com/github.com/RadiusNetworks/hello-proximity-cordova. (It should only take 30 seconds.)

Thank you!

**Comment by jnebeker** [comment]
Sourcegraph has been enabled for this repo
