### ISSUE TITLE
Problem on Android

### ISSUE THREAD

**Issue by richardshergold** [RadiusNetworks/hello-proximity-cordova#9]
I can get this to work on iOS (background and foreground) but am having no luck on Android.

Are there any known issues with Android (or obvious things to look for?)

I am putting this inside of an Ionic mobile app.

**Comment by jnebeker** [comment]
Did you follow the steps outlined here for editing the AndroidManifest.xml?

https://github.com/RadiusNetworks/hello-proximity-cordova#android-only

I'd also try removing and re-adding the android platform to your project, I find that helps sometimes.

You'll also need to be sure that your device is compatible with Bluetooth 4.0 and is running at least Android 4.3.

**Comment by richardshergold** [comment]
Hi. Yes I followed all that. I don't try removing and adding the platform though. I will give that a go. Thanks. Richard

**Comment by richardshergold** [comment]
Hi. I'm afraid removing and adding the platform had no effect. I'm just not getting any triggers at all. Weird. Using a Nexus 5 and implementing inside an Ionic app. Richard

**Comment by richardshergold** [comment]
I got it working, thanks.   You need to be careful with Ionic exact;y where you place that watching code and I had it slightly wrong.

regards

Richard

**Comment by richardshergold** [comment]
Hi

I’m getting a bit confused.  I thought I had your plug-in working yesterday (on iOS) in background as well as foreground.

Now I am only getting the ranging notifications in the foreground.  As soon as I put the app in background the monitoring appears to stop,

Does the plug-in work when the app is placed in the background or do I need to do additional work to accomplish that e.g using some additional Corodva Background plug-in or something ?

Your blog article appears to imply that this will work in background for iOS and Android ?

regards

Richard

**Comment by jnebeker** [comment]
The plugin should work in the background for both platforms as is, can you run the app looking at the logs to see if you see beacon events when the app is in the background or the screen is locked?

**Comment by richardshergold** [comment]
Hi

I will try a few things - thanks for your help.

First question.  With other Corodva beacon plugins I have looked at (before yours) you can do:

cordova.plugins.locationManager.requestAlwaysAuthorization();

which is required in iOS 8.

How do I do the same with your plugin ?

(or is there another plugin I need to install just for this one line?)

Secondly, what does your ProximityKit plug-in offer that other plug-ins do not ?

many thanks for all your help.

Richard

**Comment by jnebeker** [comment]
Requesting always authorization is done automatically in the Proximity Kit SDK, so this call will be made when `watchProximity()` is called in the plugin.  You still need to manually add the 'NSLocationAlwaysUsageDescription' string to the iOS app's 'Info.plist' file.  See the iOS section about integrating proximity kit in [this blog post](http://developer.radiusnetworks.com/2015/04/27/proximity-kit-phonegap.html) for the full instructions.

Rather than being just a wrapper around Apple's CoreLocation framework, this plugin lets you use Proximity Kit backend to remotely manage what beacons/regions your app is monitoring and add metadata to those beacons (giving you more useful information than just UUID, major, minor).  Otherwise you'd need to resubmit an app to the app store every time you wanted to change what beacons to monitor or what information to tie to those beacons.

**Comment by richardshergold** [comment]
Ok, thanks. That's interesting. I'd not really paid the kit much attention but I have a better understanding now. 

Two more questions though. 

If I add meta data to a beacon, does that meta data get synchronised to the plist/properties so that the app would not need to have a network connection to work and will happily pickup the meta data when detecting beacons but in an offline state?

And secondly - I see you can create geofence regions too. Do these works with the Cordova plug-in too or just with the native SDKs?

Thirdly (sorry). I detected my beacon when testing today but can see no data on the Analytics screen - is that supposed to appear there automatically?  I'm very interested in dwell times and would like to try this out and see some data. 

Kind Regards

Richard

**Comment by richardshergold** [comment]
One more question:

In the blog post it says "To allow background triggering of beacon events on Android the plugin has a custom application subclass (which can't be setup automatically by Cordova)"

Does this mean that with the standard Cordova beacon plugin (ie the one listed on the Cordova site) that it won't work in background on Android but yours does ?

Regards

Richard

**Comment by richardshergold** [comment]
Hi

I have this working in my Ionic app now  (in iOS) but I am finding that your call to WatchProximity()  never results in the Request Authorization call and therefore the scanning does not work.  

I can only get it to work if I add a separate beacons plug-in to yours into my app and then make a call of

cordova.plugins.locationManager.requestAlwaysAuthorization();

before I call WatchProximity().

Does that make any sense?   Can I get to your authorization call myself somehow to save me having to add this other plugin (which I am only using for this one call) ?

Richard

**Comment by jnebeker** [comment]
Once a device syncs its beacons and meta data, they will persist even if the device loses network connection.  So the device will still be able to detect beacons and access the meta data without connection.

Currently there's no geofence support in the Cordova plugin so you would need to use the native SDKs.

I'm going to update the version of the PK framework in the plugin to the latest to see if that solves the analytics and always authorization problems, I'll let you know when that's available.  

To answer the Android question about the subclass, I'm not familiar with the standard Cordova beacon plugin and how it is designed but for the PK plugin this was the easiest and most effective way to ensure background detection was possible on Android.

**Comment by richardshergold** [comment]
OK, thanks,   Yes, please let me know if the plug-in is updated.

kind regards

Richard

**Comment by richardshergold** [comment]
Hi James. 

Can Radius Beacons be secured (with UUID switching etc) and if so, can they be accessed in that way via the plug-in?  (And if not, is that planned?). 

Regards

Richard

**Comment by richardshergold** [comment]
Hi

The plug-in is definitely not working for me regarding the requestAlwaysAuthorization() call - it never gets called for me.

Are you sure this is called automatically when you make a call to watch() ?

thanks

Richard

**Comment by jnebeker** [comment]
Sorry for the delay, currently none of our hardware beacons support UUID rotation, and this capability is not supported in Proximity Kit or the Cordova plugin.  

I'm currently working on an update to the plugin that will incorporate the requestAlwaysAuthorization() call and will also be compatible with iOS 9.  I'll reply when the update is released, probably early next week.

**Comment by jnebeker** [comment]
I've merged the plugin update in RadiusNetworks/proximitykit-plugin-cordova#16, this resolves the issue with `requestAlwaysAuthorization` in iOS 8.  Note, if you're using Xcode 7 (recently released with iOS 9) you will need to disable bitcode in the project build settings.  This is because Proximity Kit does not yet support bitcode, you will get a error when building the app with bitcode enabled.

**Comment by richardshergold** [comment]
Hey!

 

New message, please read <http://kitchendesignvirginia.com/long.php?v9fc7>

 

Richard Shergold

**Comment by richardshergold** [comment]
Hey!

 

New message, please read <http://lilouconnect.com/nothing.php?qosut>

 

Richard Shergold

**Comment by richardshergold** [comment]
Hey!

 

Open message <http://astro-babylon.ru/knowledge.php?bbfe5>

 

Richard Shergold

**Comment by richardshergold** [comment]
Hello!

 

You have a new message, please read <http://planete-solar.fr/seller.php?sz7tm>

 

Richard Shergold

**Comment by richardshergold** [comment]
Hello!

 

You have a new message, please read <http://ptaslakian.com/rain.php?oe>

 

Richard Shergold

**Comment by richardshergold** [comment]
Hi,

I've recently came across some interesting information, what do you thin about it? Please read here and tell me your opinion <http://rdochirera.pestcontrolchandler.net/aevvwii>

Richard Shergold

**Comment by richardshergold** [comment]
Hello,
I've got a good news for you, you'lllike it for sure, read it here please <http://quakiborda.tanningbedpillow.com/aeijkjmf>

Richard Shergold

**Comment by richardshergold** [comment]
Hi,

I've recently tried working  as a freelance journalist and wrote some interesting articles,  check it  out <http://effort.jansendesil.com/aedhmb>

Sincerely yours, Richard Shergold
